language: node_js
node_js:
  - '6'
install:
  - cd client
  - npm install
script:
  - npm run test
  - npm run build
after_success: 
  - npm run coveralls
cache:
  directories:
  - node_modules
branches:
  only:
  - master
